### ISSUE TITLE
integration for kommentary

### ISSUE THREAD

**Issue by yamatsum** [JoosepAlviste/nvim-ts-context-commentstring#10]
> Let me know if you'd like a similar integration for another commenting plugin.

https://github.com/b3nj5m1n/kommentary

**Comment by cloggier** [comment]
@yamatsum https://github.com/b3nj5m1n/kommentary/issues/43

No need to do anything on this plugin's side.

**Comment by yamatsum** [comment]
Thanks!
If I comment out twice in tsx, it will behave strangely.

<img width="379" alt="CleanShot 2021-06-03 at 00 59 55@2x" src="https://user-images.githubusercontent.com/42740055/120513378-30f35280-c407-11eb-9820-726b384a3b6c.png">

```
require("kommentary.config").configure_language("typescriptreact", {
    hook_function = function()
       pre_comment_hook = require('ts_context_commentstring.internal').update_commentstring()
    end,
    prefer_single_line_comments = true,
})
```

**Comment by JoosepAlviste** [comment]
The kommentary integration looks great! I'll add a note about it in the README.

@yamatsum About commenting twice in JSX, that seems to be a problem in general, not directly related to kommentary.

The issue is that if you comment the first line (only the first line) in any JSX block, then there will be a syntax error. For example, this is not valid JS/JSX:

```js
const App = () => (
  {/* <div> */}
    <p>Hello world</p>
  </div>
)
```

Now, treesitter thinks that the first line of JSX with the comment is an `object`.

I created an issue for this: https://github.com/JoosepAlviste/nvim-ts-context-commentstring/issues/11 but I don't think that it's super high priority for now. I probably won't be dealing with it any time soon.

---

Toggling comments of other bits of JSX seems to work fine though, so I hope that it's OK at the moment. Hopefully it won't be necessary to comment the first line of JSX very often 😃
