### ISSUE TITLE
[Question] Plugin to load server by context

### ISSUE THREAD

**Issue by ofrades** [JoosepAlviste/nvim-ts-context-commentstring#32]
Many thanks for this great plugin.

I was wondering if this plugin is possible, it should also be also possible to load lsp servers per treessiter context.
For example, in tsx, if we are in the markup we should be able to load the HTML and emmet servers, likewise inside
some CSS, or even if we are in an attribute of the tag, like the string in the class attribute, load the tailwind server.

I know this is not the scope of this plugin but because you are kind of doing something similar I was wondering if this would be at all possible.

**Comment by JoosepAlviste** [comment]
Hey @ofrades!

I have also thought about this subject a little bit. I think that it depends on the LSP since LSPs don't generally understand embedded languages. Vue language server has been built specifically to handle injected languages in `.vue` files.

One (extremely hacky 😄) possibility would be to copy the injected language part of the file into a new temporary file, run LSP on that file, and pass the LSP diagnostics / completion results to the current buffer. I think that that's how Vue LSP handles multiple LSPs in a single file internally. I don't know if something like that should be in a language server or maybe it could be implemented as a Neovim plugin with the help of treesitter and customized built-in LSP client.
