### ISSUE TITLE
Can I set newlines in commentstrings?

### ISSUE THREAD

**Issue by reyniersbram** [JoosepAlviste/nvim-ts-context-commentstring#53]
I want my block comments for `lua` to be like this:
```lua
--[[
some commented-out text or code
--]]
```
So I thought it would be easy to just do something like this:
```lua
require("nvim-treesitter.config").setup{
    ...
    context_commentstring = {
	...
        config = {
            lua = {
                __default = "-- %s",
                __multiline = "--[[\n%s\n]]"
            },
        },
    },
}
```
but when commenting a block of code with [Comment.nvim](https://github.com/numToStr/Comment.nvim) the newlines are replaced by spaces.

Am I doing something wrong, or is it just not possible to have newlines in a commentstring.

[This](https://github.com/reyniersbram/dotfiles/blob/1479b597374ae690bff3aaa817b987732a173367/.config/nvim/lua/config/treesitter.lua#L31) is a link to the specific code in my dotfiles repo.

**Comment by JoosepAlviste** [comment]
Hey!

I tried this out myself too and couldn't get it to work with the Lua multiline strings either:

```lua
require('Comment').setup {
  pre_hook = function()
    return [=[--[[
%s
]]]=]
  end,
}
```

I think that this plugin can't do much about this though since the commenting plugin needs to handle the `commentstring` with new lines.

I found this issue in Comment.nvim that might be similar to your use case: https://github.com/numToStr/Comment.nvim/issues/38 Maybe this helps?

But you could open an issue/feature request in the Comment.nvim repo since I don't think we could do anything about this in this plugin.

Let me know how it goes!
